### Add an assignment (simulates pasting a link and clicking "Add")
POST http://localhost:8080/api/assignments
Content-Type: application/json

{
  "link": "https://portal.emagine.org/jobs/180220/senior-data-machine-learning-engineer",
  "technologies": ["Java"],
  "skillMatch": 4,
  "interest": null
}

### List all assignments
GET http://localhost:8080/api/assignments
